<a href="https://colab.research.google.com/github/LYZAcell/data_study/blob/main/BDA(%ED%8C%90%EB%8B%A4%EC%8A%A4)/%EB%B3%B5%EC%8A%B5_%EC%9D%B4%EA%B0%80%EC%98%8141_1229.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 공지

1. 방학 일정 : slack 콜라보, 여러 부트캠프 참여 요망
2. 10기 모집 예정: 트랙 세분화 예정
  - 데이터 리터러시 영역
  - 프로그래밍
  - 데이터분석 트랙
  - 데이터 사이언스 트랙
  - AI 트랙
3. 임원진 모집 중

# 수업
## 데이터 병합 (Merge)

조건에 따라 아래의 함수를 선택하여 쓰면 된다
- 다만 잘못된 방법으로 병합할 시 문제 발생
- 병합은 필수적인 요소. 머신러닝 분야는 필수로 병합과정이 들어가고 분석에서도 필수적인 분야
- 원하는 데이터셋을 구성하기 위해서는 필수적이다.

## 병합 함수들
- concat
- merge
- join

## 코드

In [3]:
import pandas as pd

In [4]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df2 = pd.DataFrame({'A':[4,5],'B':[6,7]})
df3 = pd.DataFrame({'A':[11,12],'B':[6,7],'C':[100,200]})

### Concat:  덩어리 + 덩어리 ( 데이터 프레임 + 데이터프레임)
데이터프레임

+

데이터프레임 형식으로 붙는다

- 축 지정이 필요하다. axis = 0 (행) or 1 (열 기준)
- concat 후 N/A값과 index에 유의 해야한다 ( 기존의 인덱스를 유지하여 0,1,2, 0-1을 유지할 수도 )

In [5]:
display(df1, df2, df3)

A  B
0  1  4
1  2  5
2  3  6

A  B
0  4  6
1  5  7

A  B    C
0  11  6  100
1  12  7  200

In [6]:
# df1 + df2
pd. concat([df1, df2], axis = 0) # 행기준 _ 인덱싱이 0 1 2 - 0, 1이라 concat이후에는 꼭 indexing확인 필요

A  B
0  1  4
1  2  5
2  3  6
0  4  6
1  5  7

In [7]:
pd.concat([df1, df2], axis = 1) # 이렇게 잘못설계해 붙이면 N/A가 발생해 곤란해질 수 있다

A  B    A    B
0  1  4  4.0  6.0
1  2  5  5.0  7.0
2  3  6  NaN  NaN

In [8]:
# 세개 합병
display(pd.concat([df1, df2, df3], axis = 0))

A  B      C
0   1  4    NaN
1   2  5    NaN
2   3  6    NaN
0   4  6    NaN
1   5  7    NaN
0  11  6  100.0
1  12  7  200.0

In [9]:
display(pd.concat([df1, df2, df3], axis = 1)) # NAN값에 유의해야한다.

A  B    A    B     A    B      C
0  1  4  4.0  6.0  11.0  6.0  100.0
1  2  5  5.0  7.0  12.0  7.0  200.0
2  3  6  NaN  NaN   NaN  NaN    NaN

In [10]:
## 인덱스 재정렬 _ ignore_index = True 해주기
display(pd.concat([df1, df2, df3], axis = 1, ignore_index = True))

0  1    2    3     4    5      6
0  1  4  4.0  6.0  11.0  6.0  100.0
1  2  5  5.0  7.0  12.0  7.0  200.0
2  3  6  NaN  NaN   NaN  NaN    NaN

### Merge

- Concat과의 차이점: join이 가능하다
  - sql, pk, 공통의 컬럼으로 데이터를 병합할 수 있다
- 공통의 컬럼 기준이 필요할 것
- 그 컬럼의 기준을 통해서 데이터를 병합하기
- **처음 작성한 데이터프레임이 기준이 된다** (= 첫번재가 된다)
  - ignore_index 가 필요없다

- left - 병합한 첫번째 프레임
- right : 병합한 두번째 데이터 프레임
- how: 병합 방식 옵션, default = inner, 기타 left, right, outer이 있다
- on: 공통 컬럼 지정하기. (지정하지 않을 시 알아서 공통열을 사용한다) _ 어지간히 병합할 때 지정해주는 게 좋다
- left_on : 공통열을 지정하는데 두 테이블의 컬럼명이 다르지만 공통인 경우에는 직접 지정해서 컬럼 세팅이 필요하다
- right_on : 비슷하지만 오른쪽으로 붙여주는 역할
- left_index:  인덱스로 병합하기
- right_index: 마찬가지

In [11]:
df1 = pd.DataFrame({'이름':['홍길동','박길동','이길동','최길동','오길동'],
                   '분반':['프로그래밍','데이터분석','데이터사이언스','인공지능','데이터리터러시']})

df2 = pd.DataFrame({'이름':['홍길동','박길동','이길동','최길동','오길동'],
                   '점수':[100,80,90,80,75]})

In [13]:
## 기본적인 merge
## 알아서 공통의 컬럼이 이름이기 때문에 잡아준다.
pd.merge(df1,df2)

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동    데이터분석   80
2  이길동  데이터사이언스   90
3  최길동     인공지능   80
4  오길동  데이터리터러시   75

In [12]:
pd.merge(df1, df2, how = 'inner')

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동    데이터분석   80
2  이길동  데이터사이언스   90
3  최길동     인공지능   80
4  오길동  데이터리터러시   75

In [ ]:
pd.merge(df1, df2, how = 'left')

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동   빅데이터분석   80
2  이길동       통계   90
3  최길동     인공지능   75
4  오길동  데이터리터러시   85

In [ ]:
pd.merge(df1, df2, how = 'outer')

이름       분반   점수
0  박길동   빅데이터분석   80
1  오길동  데이터리터러시   85
2  이길동       통계   90
3  최길동     인공지능   75
4  홍길동    프로그래밍  100

In [ ]:
pd.merge(df1, df2, how = 'right')

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동   빅데이터분석   80
2  이길동       통계   90
3  최길동     인공지능   75
4  오길동  데이터리터러시   85

In [14]:
## 데이터가 다른 케이스의 예외들 살펴보기

df1 = pd.DataFrame({'이름':['홍길동','박길동','이길동','최길동','오길동'],
                   '분반':['프로그래밍','데이터분석','데이터사이언스','인공지능','데이터리터러시']})

df2 = pd.DataFrame({'이름':['홍길동','박길동','이길동','유길동','김길동'],
                   '점수':[100,80,90,80,75]})

df3 = pd.DataFrame({'이름':['홍길동','임길동','이길동','유길동','김길동'],
                   '벌점':[5,10,2,6,9]})

In [15]:
display(df1, df2, df3)

이름       분반
0  홍길동    프로그래밍
1  박길동    데이터분석
2  이길동  데이터사이언스
3  최길동     인공지능
4  오길동  데이터리터러시

이름   점수
0  홍길동  100
1  박길동   80
2  이길동   90
3  유길동   80
4  김길동   75

이름  벌점
0  홍길동   5
1  임길동  10
2  이길동   2
3  유길동   6
4  김길동   9

In [16]:
pd.merge(df1,df2)

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동    데이터분석   80
2  이길동  데이터사이언스   90

In [17]:
display(df1, df2, df3)

이름       분반
0  홍길동    프로그래밍
1  박길동    데이터분석
2  이길동  데이터사이언스
3  최길동     인공지능
4  오길동  데이터리터러시

이름   점수
0  홍길동  100
1  박길동   80
2  이길동   90
3  유길동   80
4  김길동   75

이름  벌점
0  홍길동   5
1  임길동  10
2  이길동   2
3  유길동   6
4  김길동   9

In [18]:
#how inner 교집합
pd.merge(df1,df2, how='inner')

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동    데이터분석   80
2  이길동  데이터사이언스   90

In [19]:
pd.merge(df1,df2, how='left')

이름       분반     점수
0  홍길동    프로그래밍  100.0
1  박길동    데이터분석   80.0
2  이길동  데이터사이언스   90.0
3  최길동     인공지능    NaN
4  오길동  데이터리터러시    NaN

In [20]:
pd.merge(df1,df2, how='right')

이름       분반   점수
0  홍길동    프로그래밍  100
1  박길동    데이터분석   80
2  이길동  데이터사이언스   90
3  유길동      NaN   80
4  김길동      NaN   75

## Join

- 알아두면 좋지만 index 등의 제한으로 대부분의 경우 merge가 선호됨
- df간에 중복데이터가 있다면 : 같은 데이터 중복이 생긴다
  - 공통 사용 컬럼 pk에 중복값을 ㅘㄱ인해야함
  - df1에 홍길동, 프로그래밍  100 , df2에 홍길동, 데분, 80 있으면 merge하면 표 개수가 늘어난다
  - on - 병합할 때 사용할 열 이름, 지정하지 않으면 인덱스 기준으로 병합
- how - 동일
- suffix - 컬럼을 지정하라는 뜻"

In [30]:
## 공통 컬럼 join도 2개 이상으로 만들 수 있다.

df1 = pd.DataFrame({'이름':['홍길동','박길동','이길동','최길동','오길동'],
                    '학번':[1,2,3,4,5],
                   '분반':['프로그래밍','데이터분석','데이터사이언스','인공지능','데이터리터러시']})

df2 = pd.DataFrame({'이름':['홍길동','박길동','이길동','유길동','김길동'],
                    '학번':[1,2,3,7,8],
                   '점수':[100,80,90,80,75]})

df3 = pd.DataFrame({'이름':['홍길동','임길동','이길동','유길동','김길동'],
                   '벌점':[5,10,2,6,9]})

In [22]:
display(df1, df2)

이름  학번       분반
0  홍길동   1    프로그래밍
1  박길동   2    데이터분석
2  이길동   3  데이터사이언스
3  최길동   4     인공지능
4  오길동   5  데이터리터러시

이름  학번   점수
0  홍길동   1  100
1  박길동   2   80
2  이길동   3   90
3  유길동   7   80
4  김길동   8   75

In [23]:
pd.merge(df1,df2,on=['이름','학번']) # on 안에 두 개 이상 Join 컬럼이 필요하면 작성하시면 된다.

이름  학번       분반   점수
0  홍길동   1    프로그래밍  100
1  박길동   2    데이터분석   80
2  이길동   3  데이터사이언스   90

In [33]:
df2 = pd.DataFrame({'이름':['홍길동','박길동','이길동','유길동','김길동'],
                    '학회원학번':[1,2,3,7,8],
                   '점수':[100,80,90,80,75]})

df3 = pd.DataFrame({'학생이름':['홍길동','임길동','이길동','유길동','김길동'],
                    '분반학번':[1,8,3,7,8],
                    '벌점':[5,10,2,6,9]})

In [25]:
display(df2, df3)

이름  학회원학번   점수
0  홍길동      1  100
1  박길동      2   80
2  이길동      3   90
3  유길동      7   80
4  김길동      8   75

학생이름  분반학번  벌점
0  홍길동     1   5
1  임길동     8  10
2  이길동     3   2
3  유길동     7   6
4  김길동     8   9

In [26]:
display(df2, df3)

이름  학회원학번   점수
0  홍길동      1  100
1  박길동      2   80
2  이길동      3   90
3  유길동      7   80
4  김길동      8   75

학생이름  분반학번  벌점
0  홍길동     1   5
1  임길동     8  10
2  이길동     3   2
3  유길동     7   6
4  김길동     8   9

In [27]:
pd.merge(df2, df3, left_on ='이름',right_on='학생이름', how='outer')

이름  학회원학번     점수 학생이름  분반학번    벌점
0  김길동    8.0   75.0  김길동   8.0   9.0
1  박길동    2.0   80.0  NaN   NaN   NaN
2  유길동    7.0   80.0  유길동   7.0   6.0
3  이길동    3.0   90.0  이길동   3.0   2.0
4  NaN    NaN    NaN  임길동   8.0  10.0
5  홍길동    1.0  100.0  홍길동   1.0   5.0

In [28]:
##index 기준으로 지정할 수 있다.

df2_idx =df2.set_index('이름') # 데이터프레임에서 인덱스를 지정하는 것
df2_idx.reset_index() #인덱스를 다시 푸는 방법

이름  학회원학번   점수
0  홍길동      1  100
1  박길동      2   80
2  이길동      3   90
3  유길동      7   80
4  김길동      8   75

In [29]:
#인덱스가 지정된 경우에는 left_index 인자 이용해서 병합할 수 있다.
pd.merge(df2_idx, df3, left_index=True, right_on='학생이름')

학회원학번   점수 학생이름  분반학번  벌점
0      1  100  홍길동     1   5
2      3   90  이길동     3   2
3      7   80  유길동     7   6
4      8   75  김길동     8   9

In [34]:
df2.join(df3) #지정을 하지 않고 바로 join을 하면 인덱스 기준으로 합쳐서 모든 값들이 다 출력이 되었다.

이름  학회원학번   점수 학생이름  분반학번  벌점
0  홍길동      1  100  홍길동     1   5
1  박길동      2   80  임길동     8  10
2  이길동      3   90  이길동     3   2
3  유길동      7   80  유길동     7   6
4  김길동      8   75  김길동     8   9

In [35]:
#컬럼을 지정하지 않으면 계속해서 인덱스 기준으로 붙여진다.
#df2.join(df3, how='inner', on='이름')


df2 = pd.DataFrame({'이름':['홍길동','박길동','이길동','유길동','김길동'],
                    '학회원학번':[1,2,3,7,8],
                   '점수':[100,80,90,80,75]})

df3 = pd.DataFrame({'이름':['홍길동','임길동','이길동','유길동','김길동'],
                    '분반학번':[1,8,3,7,8],
                    '벌점':[5,10,2,6,9]})

In [36]:
# 인덱스를 '이름'으로 설정 후 join 수행
df2_indexed = df2.set_index('이름')
df3_indexed = df3.set_index('이름')

# inner join
result = df2_indexed.join(df3_indexed, how='inner')
print(result)


     학회원학번   점수  분반학번  벌점
이름                       
홍길동      1  100     1   5
이길동      3   90     3   2
유길동      7   80     7   6
김길동      8   75     8   9


In [37]:
result_outer = df2_indexed.join(df3_indexed, how='outer')
print(result_outer)
# 기타 inner, right, outer 등 가능

     학회원학번     점수  분반학번    벌점
이름                           
김길동    8.0   75.0   8.0   9.0
박길동    2.0   80.0   NaN   NaN
유길동    7.0   80.0   7.0   6.0
이길동    3.0   90.0   3.0   2.0
임길동    NaN    NaN   8.0  10.0
홍길동    1.0  100.0   1.0   5.0


In [38]:
result_suffixes = df2_indexed.join(df3_indexed, how='inner', lsuffix='_df2', rsuffix='_df3')
print(result_suffixes)

     학회원학번   점수  분반학번  벌점
이름                       
홍길동      1  100     1   5
이길동      3   90     3   2
유길동      7   80     7   6
김길동      8   75     8   9


In [39]:
## 데이터 프레임을 세 개 정도 한 번에 합치고 싶은 경우!

df1 = pd.DataFrame({'이름':['홍길동','박길동','이길동','최길동','오길동'],
                   '분반':['프로그래밍','데이터분석','데이터사이언스','인공지능','데이터리터러시']})

df2 = pd.DataFrame({'이름':['홍길동','박길동','이길동','유길동','김길동'],
                   '점수':[100,80,90,80,75]})

df3 = pd.DataFrame({'이름':['홍길동','임길동','이길동','유길동','김길동'],
                   '벌점':[5,10,2,6,9]})

In [40]:
from functools import reduce

#병합할 데이터프레임을 한 번에 넣는다.

dfs =[df1, df2, df3]
mg_df_all =reduce(lambda left, right : pd.merge(left, right, on='이름',how='inner'),dfs)

In [41]:
# 중복되는거 찾기
df3['이름'].drop_duplicates()

0    홍길동
1    임길동
2    이길동
3    유길동
4    김길동
Name: 이름, dtype: object

In [42]:
df1_d = pd.DataFrame({'이름':['홍길동','홍길동','홍길동','최길동','오길동'],
                   '분반':['프로그래밍','데이터분석','데이터사이언스','인공지능','데이터리터러시']})

df2_d = pd.DataFrame({'이름':['홍길동','이길동','이길동','유길동','김길동'],
                   '점수':[100,80,90,80,75]})

df3_d = pd.DataFrame({'이름':['홍길동','임길동','이길동','유길동','유길동'],
                   '벌점':[5,10,2,6,9]})

In [43]:
####데이터를 병합하실 때 꼭 pk 공통으로 사용할 컬럼이 중복값이 있는지를 사전에 확인을 해야 한다!아래의 예시와 같이 잘못 merge되면 찾기 어려움
pd.merge(df1_d, df2_d)

이름       분반   점수
0  홍길동    프로그래밍  100
1  홍길동    데이터분석  100
2  홍길동  데이터사이언스  100

In [44]:
pd.merge(df2_d, df3_d)

이름   점수  벌점
0  홍길동  100   5
1  이길동   80   2
2  이길동   90   2
3  유길동   80   6
4  유길동   80   9

### numpy 데이터 병합

- 메모리 효율이 넘파이가 더 좋아 자주 사용된다
- array배열로 1차원, 2차원 간의 연산, 병합 진행 시 주로 사용
- np.concatenate, np.hstack, np.vstack

In [46]:
import numpy as np

In [47]:
# concatenate 연산필기
# column_stack

array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])

In [48]:
np.concatenate((array1, array2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
np.concatenate((array1, array2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [50]:
np.hstack((array1, array2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [51]:
np.vstack((array1, array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
##컬럼으로 나눠서 데이터를 병합할 수 있다.
np.column_stack((array1[0], array2[0]))

array([[1, 7],
       [2, 8],
       [3, 9]])

In [53]:
array1[0]

array([1, 2, 3])

In [54]:
array2[0]

array([7, 8, 9])

In [55]:
np.column_stack((array1[1], array2[1]))

array([[ 4, 10],
       [ 5, 11],
       [ 6, 12]])