<a href="https://colab.research.google.com/github/LYZAcell/data_study/blob/main/BDA(%ED%8C%90%EB%8B%A4%EC%8A%A4)/%EA%B3%BC%EC%A0%9C/%EB%B3%B5%EC%8A%B5_%EC%9D%B4%EA%B0%80%EC%98%8141_0209_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
#nltk 라이브러리
nltk.download('punkt')
nltk.download('webtext')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /Users/jun/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package webtext to /Users/jun/nltk_data...
[nltk_data]   Package webtext is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/jun/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/jun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/jun/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
'Deep learning is the subset of machine learning methods based on artificial neural networks with representation learning. The adjective "deep" refers to the use of multiple layers in the network. Methods used can be either supervised, semi-supervised or unsupervised'

'Deep learning is the subset of machine learning methods based on artificial neural networks with representation learning. The adjective "deep" refers to the use of multiple layers in the network. Methods used can be either supervised, semi-supervised or unsupervised'

In [ ]:
## 어간 추출
## 어형이 단어의 형태를 의미함, 어간은(stem) 어형 변화에서 변화하지 않는 부분을 말하는 것
## cooking -> cook
## 작다. 작으니, 작고, 작아서 등등
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [ ]:
stemmer=PorterStemmer()

In [ ]:
print(stemmer.stem('cooking'),stemmer.stem('cooked'),stemmer.stem('cooker'))

cook cook cooker


In [ ]:
##표제어 추출
## 단어의 기본형
lemma=WordNetLemmatizer()

print(lemma.lemmatize('cooking'),lemma.lemmatize('cooked'),lemma.lemmatize('cooker'))

cooking cooked cooker


In [ ]:
print(lemma.lemmatize('cooking',pos='v'),lemma.lemmatize('cooked'),lemma.lemmatize('cooker'))

cook cooked cooker


In [ ]:
##품사태깅
##토큰화, 정규화를 통해서 ->결과가 나온 것을 형태소로 본다.
##형태소는 의미를 가진 가장 작은 말의 단위 -> 의미를 더 나누게 되면 본래의 뜻을 잃을 수 있다.
##책가방 책+가방 ->형태소로 볼 수 있음
##가방 가+방 ->형태소로 볼 수 없다.
## '명사, 대명사, 수사, 조사, 형용사. 관형사, 부사 등등' 공통된 성질을 지닌 낱말들끼리 모아 놓은 것들

from nltk.tokenize import word_tokenize
tokens =word_tokenize('Deep learning is the subset of machine learning methods based on artificial neural networks with representation learning. The adjective "deep" refers to the use of multiple layers in the network. Methods used can be either supervised, semi-supervised or unsupervised')

In [ ]:
print(nltk.pos_tag(tokens))

[('Deep', 'JJ'), ('learning', 'NN'), ('is', 'VBZ'), ('the', 'DT'), ('subset', 'NN'), ('of', 'IN'), ('machine', 'NN'), ('learning', 'VBG'), ('methods', 'NNS'), ('based', 'VBN'), ('on', 'IN'), ('artificial', 'JJ'), ('neural', 'JJ'), ('networks', 'NNS'), ('with', 'IN'), ('representation', 'NN'), ('learning', 'NN'), ('.', '.'), ('The', 'DT'), ('adjective', 'JJ'), ('``', '``'), ('deep', 'JJ'), ("''", "''"), ('refers', 'NNS'), ('to', 'TO'), ('the', 'DT'), ('use', 'NN'), ('of', 'IN'), ('multiple', 'JJ'), ('layers', 'NNS'), ('in', 'IN'), ('the', 'DT'), ('network', 'NN'), ('.', '.'), ('Methods', 'NNS'), ('used', 'VBD'), ('can', 'MD'), ('be', 'VB'), ('either', 'RB'), ('supervised', 'VBN'), (',', ','), ('semi-supervised', 'JJ'), ('or', 'CC'), ('unsupervised', 'JJ')]


In [ ]:
nltk.help.upenn_tagset('CC')

CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet


### 한글을 가지고 형태소를 분석하고 품사를 태깅해 보자!

- KoNLPy -한국어 형태소 분석 및 품사 태깅 라이브러리
- Kkma, Komoran, Twitter, Mecab, Hannaum, Okt

- https://konlpy.org/ko/latest/

In [ ]:
from konlpy.tag import Okt

k=Okt()

- morphs(phrase)-> 형태소 단위로 분리 -> 형태소의 리스트
- nouns(phrase) -> 형태소 단위로 분리해서 명사만 반환
- pos(pharse) ->형태소 분리하고 품사 부착해서 반환

In [ ]:
data="""[BDA 10기 모집 오픈채팅방 운영 기간 연장 안내]

안녕하세요, BDA 운영진입니다.

BDA 10기 모집을 위한 오픈 카카오톡 채팅방 운영 기간이 연장되었습니다!
기존 2월 7일(금) → 2월 18일(화)까지로 연장되었으니, 아직 참여하지 못한 분들은 기회를 놓치지 마세요.

이번 모집 연장은 2월부터 시작될 다양한 행사 및 활동에 더 많은 학회원들이 참여할 수 있도록 하기 위한 결정입니다. 관심 있는 분들은 꼭 참여해 주세요!

🔹 [BDA 10기 모집 일정 재안내]
📌 1/13 ~ 2/18 : 모집 오픈채팅방 링크 공지
📌 2/5 ~ 2/11 : 분반 수요 조사
📌 2/12 ~ 2/18 : 실제 모집 진행 (12일부터 구글 폼 공유 예정)
📌 3/5 ~ 3/8 : 첫 수업 진행
📌 3/5 ~ 3/12 : 환불 및 분반 변경 기간

📢 참여를 원하시는 분들은 오픈채팅방을 통해 최신 정보를 확인해 주세요!
많은 관심과 참여 부탁드립니다. 😊"""

In [ ]:
print(data)
print(k.nouns(data))

[BDA 10기 모집 오픈채팅방 운영 기간 연장 안내]

안녕하세요, BDA 운영진입니다.

BDA 10기 모집을 위한 오픈 카카오톡 채팅방 운영 기간이 연장되었습니다!
기존 2월 7일(금) → 2월 18일(화)까지로 연장되었으니, 아직 참여하지 못한 분들은 기회를 놓치지 마세요.

이번 모집 연장은 2월부터 시작될 다양한 행사 및 활동에 더 많은 학회원들이 참여할 수 있도록 하기 위한 결정입니다. 관심 있는 분들은 꼭 참여해 주세요!

🔹 [BDA 10기 모집 일정 재안내]
📌 1/13 ~ 2/18 : 모집 오픈채팅방 링크 공지
📌 2/5 ~ 2/11 : 분반 수요 조사
📌 2/12 ~ 2/18 : 실제 모집 진행 (12일부터 구글 폼 공유 예정)
📌 3/5 ~ 3/8 : 첫 수업 진행
📌 3/5 ~ 3/12 : 환불 및 분반 변경 기간

📢 참여를 원하시는 분들은 오픈채팅방을 통해 최신 정보를 확인해 주세요!
많은 관심과 참여 부탁드립니다. 😊
['기', '모집', '오픈', '채팅', '방', '운영', '기간', '연장', '안내', '운영', '진입', '니', '기', '모집', '위', '오픈', '카카오', '톡', '채팅', '방', '운영', '기간', '연장', '기존', '금', '화', '연장', '참여', '못', '분', '기회', '이번', '모집', '연장', '시작', '행사', '및', '활동', '더', '학회', '참여', '수', '위', '결정', '관심', '분', '꼭', '참여', '기', '모집', '일정', '모집', '오픈', '채팅', '방', '링크', '공지', '분반', '수요', '조사', '실제', '모집', '진행', '구글', '폼', '공유', '예정', '첫', '수업', '진행', '환불', '및', '분반', '변경', '기간', '참여', '분', '오픈', '채팅', '방', '통해', '최신', '정보', '확인', '관심', '참여']


In [ ]:
print(k.pos(data))

[('[', 'Punctuation'), ('BDA', 'Alpha'), ('10', 'Number'), ('기', 'Noun'), ('모집', 'Noun'), ('오픈', 'Noun'), ('채팅', 'Noun'), ('방', 'Noun'), ('운영', 'Noun'), ('기간', 'Noun'), ('연장', 'Noun'), ('안내', 'Noun'), (']', 'Punctuation'), ('\n\n', 'Foreign'), ('안녕하세요', 'Adjective'), (',', 'Punctuation'), ('BDA', 'Alpha'), ('운영', 'Noun'), ('진입', 'Noun'), ('니', 'Noun'), ('다', 'Josa'), ('.', 'Punctuation'), ('\n\n', 'Foreign'), ('BDA', 'Alpha'), ('10', 'Number'), ('기', 'Noun'), ('모집', 'Noun'), ('을', 'Josa'), ('위', 'Noun'), ('한', 'Josa'), ('오픈', 'Noun'), ('카카오', 'Noun'), ('톡', 'Noun'), ('채팅', 'Noun'), ('방', 'Noun'), ('운영', 'Noun'), ('기간', 'Noun'), ('이', 'Josa'), ('연장', 'Noun'), ('되었습니다', 'Verb'), ('!', 'Punctuation'), ('\n', 'Foreign'), ('기존', 'Noun'), ('2월', 'Number'), ('7일', 'Number'), ('(', 'Punctuation'), ('금', 'Noun'), (')', 'Punctuation'), ('→', 'Foreign'), ('2월', 'Number'), ('18일', 'Number'), ('(', 'Punctuation'), ('화', 'Noun'), (')', 'Punctuation'), ('까지로', 'Josa'), ('연장', 'Noun'), ('되었으니', 'Verb'

In [ ]:
import pandas as pd
df=pd.read_csv('movie_rv.csv')

In [ ]:
df_sp=df.iloc[:10000]

## 문서를 임베딩하는 방법
- Bow( Bag of Words)
    - 카운트기반의 문서 표현
- CountVectorizer 패키지를 가지고 간단하게 표현할 수 있다.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#예시 샘플 데이터

corpus =[
    'This is the first corpus',
    'This corpus is the second corpus',
    'And this corpus is the third one',
    'Is this the sencond corpus?'
]

In [ ]:
corpus

['This is the first corpus',
 'This corpus is the second corpus',
 'And this corpus is the third one',
 'Is this the sencond corpus?']

In [ ]:
c=CountVectorizer()

In [ ]:
#벡터화해서 만들어 준다.
X=c.fit_transform(corpus)

In [ ]:
print('corpus에서 사용한 피처는 무엇인지 보고 싶다!', c.get_feature_names_out())

corpus에서 사용한 피처는 무엇인지 보고 싶다! ['and' 'corpus' 'first' 'is' 'one' 'second' 'sencond' 'the' 'third' 'this']


In [ ]:
print('어떤 식으로 메트릭스가 만들어졌나?', X)

어떤 식으로 메트릭스가 만들어졌나?   (0, 9)	1
  (0, 3)	1
  (0, 7)	1
  (0, 2)	1
  (0, 1)	1
  (1, 9)	1
  (1, 3)	1
  (1, 7)	1
  (1, 1)	2
  (1, 5)	1
  (2, 9)	1
  (2, 3)	1
  (2, 7)	1
  (2, 1)	1
  (2, 0)	1
  (2, 8)	1
  (2, 4)	1
  (3, 9)	1
  (3, 3)	1
  (3, 7)	1
  (3, 1)	1
  (3, 6)	1


In [ ]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 1, 1, 0, 1]])

In [ ]:
corpus

['This is the first corpus',
 'This corpus is the second corpus',
 'And this corpus is the third one',
 'Is this the sencond corpus?']

In [ ]:
## 한국어 진행
corpus_ko =[
    '오늘 날씨 너무 추워요.',
    '내일 날씨 너무 추울까요?',
    '내일은 덜 추우면 좋겠다.',
    '모두 내일은 방학인가요?',
    '방학에는 공부를 열심히 해야죠!',
    'BDA도 방학에 공부를 더 많이 하죠',
    'BDA 10기를 모집한다고요.',
    '10기까지 왔구나',
    '10기는 다양한 사람들이 더 모일 것 같아요!'
]

In [ ]:
corpus_ko

['오늘 날씨 너무 추워요.',
 '내일 날씨 너무 추울까요?',
 '내일은 덜 추우면 좋겠다.',
 '모두 내일은 방학인가요?',
 '방학에는 공부를 열심히 해야죠!',
 'BDA도 방학에 공부를 더 많이 하죠',
 'BDA 10기를 모집한다고요.',
 '10기까지 왔구나',
 '10기는 다양한 사람들이 더 모일 것 같아요!']

In [ ]:
c=CountVectorizer()
#벡터화해서 만들어 준다.
X=c.fit_transform(corpus_ko)

In [ ]:
print('corpus에서 사용한 피처는 무엇인지 보고 싶다!', c.get_feature_names_out())
print('어떤 식으로 메트릭스가 만들어졌나?', X)

corpus에서 사용한 피처는 무엇인지 보고 싶다! ['10기까지' '10기는' '10기를' 'bda' 'bda도' '같아요' '공부를' '날씨' '내일' '내일은' '너무' '다양한'
 '많이' '모두' '모일' '모집한다고요' '방학에' '방학에는' '방학인가요' '사람들이' '열심히' '오늘' '왔구나'
 '좋겠다' '추우면' '추울까요' '추워요' '하죠' '해야죠']
어떤 식으로 메트릭스가 만들어졌나?   (0, 21)	1
  (0, 7)	1
  (0, 10)	1
  (0, 26)	1
  (1, 7)	1
  (1, 10)	1
  (1, 8)	1
  (1, 25)	1
  (2, 9)	1
  (2, 24)	1
  (2, 23)	1
  (3, 9)	1
  (3, 13)	1
  (3, 18)	1
  (4, 17)	1
  (4, 6)	1
  (4, 20)	1
  (4, 28)	1
  (5, 6)	1
  (5, 4)	1
  (5, 16)	1
  (5, 12)	1
  (5, 27)	1
  (6, 3)	1
  (6, 2)	1
  (6, 15)	1
  (7, 0)	1
  (7, 22)	1
  (8, 1)	1
  (8, 11)	1
  (8, 19)	1
  (8, 14)	1
  (8, 5)	1


In [ ]:
X.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0]])

In [ ]:
corpus_ko

['오늘 날씨 너무 추워요.',
 '내일 날씨 너무 추울까요?',
 '내일은 덜 추우면 좋겠다.',
 '모두 내일은 방학인가요?',
 '방학에는 공부를 열심히 해야죠!',
 'BDA도 방학에 공부를 더 많이 하죠',
 'BDA 10기를 모집한다고요.',
 '10기까지 왔구나',
 '10기는 다양한 사람들이 더 모일 것 같아요!']

## TF-IDF
- (Term Frequency - Inverse Document Frequency)
- 일종의 가중치를 사용하는 것
- 카운트 벡터에서 빈도가 높을수록 중요한 단어로 생각하는데 -> 이게 정말 중요한 단어입니까?
- 단어가 더 많은 문서에서 나타날수록 그 단어는 별로 중요하지 않게 된다. 이러한 의미를 카운트 벡터에 반영한 것이 TF-IDF
- 단어빈도- 역문서빈도
- 카운트 대신 단어의 빈도에 그 단어가 출현한 문서 수의 역수를 곱했다.
- 단어가 나타난 문서의 수가 클수록 이 값은 작아진다.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
corpus_ko

['오늘 날씨 너무 추워요.',
 '내일 날씨 너무 추울까요?',
 '내일은 덜 추우면 좋겠다.',
 '모두 내일은 방학인가요?',
 '방학에는 공부를 열심히 해야죠!',
 'BDA도 방학에 공부를 더 많이 하죠',
 'BDA 10기를 모집한다고요.',
 '10기까지 왔구나',
 '10기는 다양한 사람들이 더 모일 것 같아요!']

In [ ]:
tfidf=TfidfVectorizer()

In [ ]:
tfidf_X=tfidf.fit_transform(corpus_ko)

In [ ]:
tfidf_X

<9x29 sparse matrix of type '<class 'numpy.float64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [ ]:
print('corpus에서 사용한 피처는 무엇인지 보고 싶다!', tfidf.get_feature_names_out())
print('어떤 식으로 메트릭스가 만들어졌나?', tfidf_X)

corpus에서 사용한 피처는 무엇인지 보고 싶다! ['10기까지' '10기는' '10기를' 'bda' 'bda도' '같아요' '공부를' '날씨' '내일' '내일은' '너무' '다양한'
 '많이' '모두' '모일' '모집한다고요' '방학에' '방학에는' '방학인가요' '사람들이' '열심히' '오늘' '왔구나'
 '좋겠다' '추우면' '추울까요' '추워요' '하죠' '해야죠']
어떤 식으로 메트릭스가 만들어졌나?   (0, 26)	0.5402050699288926
  (0, 10)	0.4562658023818137
  (0, 7)	0.4562658023818137
  (0, 21)	0.5402050699288926
  (1, 25)	0.5402050699288926
  (1, 8)	0.5402050699288926
  (1, 10)	0.4562658023818137
  (1, 7)	0.4562658023818137
  (2, 23)	0.6070787148636269
  (2, 24)	0.6070787148636269
  (2, 9)	0.5127483475537044
  (3, 18)	0.6070787148636269
  (3, 13)	0.6070787148636269
  (3, 9)	0.5127483475537044
  (4, 28)	0.5189380717981641
  (4, 20)	0.5189380717981641
  (4, 6)	0.438303357179945
  (4, 17)	0.5189380717981641
  (5, 27)	0.4606106279676078
  (5, 12)	0.4606106279676078
  (5, 16)	0.4606106279676078
  (5, 4)	0.4606106279676078
  (5, 6)	0.3890390695202013
  (6, 15)	0.5773502691896258
  (6, 2)	0.5773502691896258
  (6, 3)	0.5773502691896258
  (7, 22)	0.7071067811865

In [ ]:
tfidf_X.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4562658 , 0.        , 0.        ,
        0.4562658 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.54020507, 0.        , 0.        , 0.        ,
        0.        , 0.54020507, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4562658 , 0.54020507, 0.        ,
        0.4562658 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.54020507, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.51274835,
        0.        , 0.        , 0.        , 0.        , 0.        ,
  

In [ ]:
stop_words = ['bda도']
##stop_words, min_df 최소 1회 이상 최소의 횟수를 나타나는 단어만 포함, ngram 주변 단어를 같이 묶어서 벡터 학습
tfidf_tun=TfidfVectorizer(stop_words = stop_words, min_df =2, ngram_range=(1,2))

In [ ]:
X_tun=tfidf_tun.fit_transform(corpus_ko)

In [ ]:
X_tun

<9x5 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [ ]:
print('corpus에서 사용한 피처는 무엇인지 보고 싶다!', tfidf_tun.get_feature_names_out())
print('어떤 식으로 메트릭스가 만들어졌나?', X_tun)

corpus에서 사용한 피처는 무엇인지 보고 싶다! ['공부를' '날씨' '날씨 너무' '내일은' '너무']
어떤 식으로 메트릭스가 만들어졌나?   (0, 2)	0.5773502691896257
  (0, 4)	0.5773502691896257
  (0, 1)	0.5773502691896257
  (1, 2)	0.5773502691896257
  (1, 4)	0.5773502691896257
  (1, 1)	0.5773502691896257
  (2, 3)	1.0
  (3, 3)	1.0
  (4, 0)	1.0
  (5, 0)	1.0


In [ ]:
corpus_ko

['오늘 날씨 너무 추워요.',
 '내일 날씨 너무 추울까요?',
 '내일은 덜 추우면 좋겠다.',
 '모두 내일은 방학인가요?',
 '방학에는 공부를 열심히 해야죠!',
 'BDA도 방학에 공부를 더 많이 하죠',
 'BDA 10기를 모집한다고요.',
 '10기까지 왔구나',
 '10기는 다양한 사람들이 더 모일 것 같아요!']

In [ ]:
X_tun.toarray()

array([[0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

## 필수과제1
- movie 데이터를 가지고 countvectorizer 벡터화 진행
- movie 데이터를 가지고 tf-idf 벡터화 진행

- 단 그대로 벡터를 만드는 게 아니라 전처리 진행 후 -> 차원 확인, 유의미한 형태소로 묶였는지 체크하고, 필요 없는 것들은 불용어처리로 제거하여 최대한 벡터 차원을 줄이는 것을 목표로 진행!
